In [1]:
2+1


3

In [15]:
import numpy as np
lista=[1,2,3,4,5,6,7,8]
arr=np.array(lista)

In [16]:
type(arr)

numpy.ndarray

In [19]:
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
type(lista)

list

In [7]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[0]+arr[5]

7

In [22]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[0,2]

3

In [24]:
arr[0:3]

array([1, 2, 3])

In [25]:
arr[2]

3

In [26]:
arr[2:]

array([3, 4, 5, 6, 7, 8])

In [27]:
arr[::3]

array([1, 4, 7])

In [28]:
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
arr[-1]

8

In [30]:
arr[-3]

6